import { Inter } from "next/font/google";
import "./globals.css";
import MovieHeader from "@/components/MovieHeader";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Movie",
  description: "Generated by soongon kim",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MovieHeader/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
